name: GitHub Actions for Sally
on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
  workflow_dispatch:

# Define environment variables
env:
  PYTHON_VERSION: "3.12.8"
  PIP_CACHE_DIR: "~/.cache/pip" # Default for Linux, will adjust  for MacOS"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-13, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip' # Enable built-in pip caching
          cache-dependency-path: | 
            **/requirements.txt
            **/setup.py # catches changes in install_requires

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest hio
          if [ -f requirements.txt ]; then pip install --prefer-binary -r requirements.txt; fi
        shell: bash

      - name: Lint changes
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || exit 1
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --ignore=E7,F841,E301,E302,E303 --max-complexity=10 --max-line-length=127 --statistics
        shell: bash

      - name: Run core Sally tests
        run: |
          pytest tests/
        shell: bash
