# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: GitHub Actions for Sally
on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-13, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest hio
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint changes
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --ignore=E7,F841,E301,E302,E303 --max-complexity=10 --max-line-length=127 --statistics
      - name: Run core Sally tests
        run: |
          pytest tests/
